#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/scripts/agent-roles.sh"
missing=0

required_files=(
  "AGENTS.md"
  ".agents/context-map.md"
  ".agents/agent-policy.md"
  ".agents/company/README.md"
  ".agents/company/agent-profiles.jsonl"
  ".agents/company/projects.jsonl"
  ".agents/meetings/README.md"
  ".agents/media/README.md"
  ".agents/media/manifest.jsonl"
  ".agents/approvals.jsonl"
  ".agents/evaluation-suite.md"
  ".agents/failure-recovery.md"
  ".agents/adaptation-guide.md"
  ".agents/design-notes.md"
  ".agents/product-requirements.md"
  ".agents/qa-plan.md"
  ".agents/release-notes.md"
  ".agents/research-notes.md"
  ".agents/performance-report.md"
  ".agents/intake-notes.md"
  ".agents/project-target.md"
  ".agents/brief.md"
  ".agents/sop.md"
  ".agents/roles.md"
  ".agents/architecture.md"
  ".agents/decisions.md"
  ".agents/definition-of-ready.md"
  ".agents/definition-of-done.md"
  ".agents/conflict-resolution.md"
  ".agents/task-board.md"
  ".agents/handoffs.md"
  ".agents/quality-gates.md"
  ".agents/change-control.md"
  ".agents/change-request.md"
  ".agents/workflow-state.md"
  ".agents/routing-matrix.md"
  ".agents/route-schema.md"
  ".agents/routes/README.md"
  ".agents/events.jsonl"
  ".agents/memory-policy.md"
  ".agents/sync-policy.md"
  ".agents/route-budget.md"
  ".agents/secrets-policy.md"
  ".agents/milestone-budget.md"
  ".agents/validation-report.md"
  ".agents/review-report.md"
  ".agents/security-report.md"
  ".agents/prompts/orchestrator.md"
  ".agents/prompts/intake-orchestrator.md"
  ".agents/prompts/cto.md"
  ".agents/prompts/pm.md"
  ".agents/prompts/frontend.md"
  ".agents/prompts/backend.md"
  ".agents/prompts/validation.md"
  ".agents/prompts/final-cto-review.md"
  ".agents/prompts/final-acceptance.md"
  ".agents/prompts/reviewer.md"
  ".agents/prompts/security.md"
  ".agents/prompts/integration.md"
  ".agents/agent-log/orchestrator.md"
  ".agents/agent-log/reviewer.md"
  ".agents/agent-log/security.md"
  ".agents/skills/orchestrator.md"
  ".agents/skills/cto.md"
  ".agents/skills/pm.md"
  ".agents/skills/frontend.md"
  ".agents/skills/backend.md"
  ".agents/skills/validation.md"
  ".agents/skills/reviewer.md"
  ".agents/skills/security.md"
  ".agents/skills/integration.md"
  ".agents/memory/orchestrator.md"
  ".agents/memory/cto.md"
  ".agents/memory/pm.md"
  ".agents/memory/frontend.md"
  ".agents/memory/backend.md"
  ".agents/memory/validation.md"
  ".agents/memory/reviewer.md"
  ".agents/memory/security.md"
  ".agents/memory/integration.md"
  ".agents/agent-config/orchestrator.yaml"
  ".agents/agent-config/cto.yaml"
  ".agents/agent-config/pm.yaml"
  ".agents/agent-config/frontend.yaml"
  ".agents/agent-config/backend.yaml"
  ".agents/agent-config/validation.yaml"
  ".agents/agent-config/reviewer.yaml"
  ".agents/agent-config/security.yaml"
  ".agents/agent-config/integration.yaml"
  ".agents/ownership/orchestrator.paths"
  ".agents/ownership/cto.paths"
  ".agents/ownership/pm.paths"
  ".agents/ownership/frontend.paths"
  ".agents/ownership/backend.paths"
  ".agents/ownership/validation.paths"
  ".agents/ownership/reviewer.paths"
  ".agents/ownership/security.paths"
  ".agents/ownership/integration.paths"
  ".agents/ownership/ignored-synced.paths"
  ".agents/schemas/orchestrator-output.md"
  ".agents/schemas/cto-output.md"
  ".agents/schemas/pm-output.md"
  ".agents/schemas/implementation-output.md"
  ".agents/schemas/validation-output.md"
  ".agents/schemas/reviewer-output.md"
  ".agents/schemas/security-output.md"
  ".agents/schemas/integration-output.md"
  ".agents/schemas/agent-profile.md"
  ".agents/schemas/agent-state.md"
  ".agents/schemas/meeting-output.md"
  ".agents/schemas/media-attachment.md"
  ".agents/schemas/approval-record.md"
  ".agents/state/README.md"
  ".agents/state/projects.jsonl"
  ".agents/state/agents.jsonl"
  ".agents/state/routes.jsonl"
  ".agents/state/tasks.jsonl"
  ".agents/state/findings.jsonl"
  ".agents/state/meetings.jsonl"
  ".agents/state/media.jsonl"
  ".agents/state/approvals.jsonl"
  ".agents/inbox/orchestrator.md"
  ".agents/inbox/cto.md"
  ".agents/inbox/pm.md"
  ".agents/inbox/frontend.md"
  ".agents/inbox/backend.md"
  ".agents/inbox/validation.md"
  ".agents/inbox/reviewer.md"
  ".agents/inbox/security.md"
  ".agents/inbox/integration.md"
  ".tmux.agent-team.conf"
  "scripts/start-agent-team.sh"
  "scripts/agent-roles.sh"
  "scripts/codex-role.sh"
  "scripts/watch-routes.sh"
  "scripts/company-status.sh"
  "scripts/create-meeting.sh"
  "scripts/close-meeting.sh"
  "scripts/attach-media.sh"
  "scripts/record-approval.sh"
  "scripts/new-coding-project.sh"
  "scripts/reset-agent-team-state.sh"
  "scripts/set-project-target.sh"
  "scripts/start-agent-team-worktrees.sh"
  "scripts/check-ready.sh"
  "scripts/check-done.sh"
  "scripts/run-quality-gates.sh"
  "scripts/log-event.sh"
  "scripts/update-agent-state.sh"
  "scripts/sync-agent-state.sh"
  "scripts/claim-route.sh"
  "scripts/complete-route.sh"
  "scripts/block-route.sh"
  "scripts/cancel-route.sh"
  "scripts/dispatch-routes.sh"
  "scripts/check-ownership.sh"
  "scripts/check-memory.sh"
  "scripts/check-route-budget.sh"
  "scripts/check-stale-routes.sh"
  "scripts/recover-stale-routes.sh"
  "scripts/check-agent-config.sh"
  "scripts/check-secrets.sh"
  "scripts/check-milestone-budget.sh"
  "scripts/validate-structured-state.sh"
  "scripts/validate-route-state.sh"
  "scripts/route-status.sh"
)

for file in "${required_files[@]}"; do
  if [ ! -f "$ROOT/$file" ]; then
    printf "Missing: %s\n" "$file" >&2
    missing=1
  fi
done

if [ "$missing" -ne 0 ]; then
  exit 1
fi

bash -n "$ROOT/scripts/start-agent-team.sh"
bash -n "$ROOT/scripts/agent-roles.sh"
bash -n "$ROOT/scripts/codex-role.sh"
bash -n "$ROOT/scripts/watch-routes.sh"
bash -n "$ROOT/scripts/company-status.sh"
bash -n "$ROOT/scripts/create-meeting.sh"
bash -n "$ROOT/scripts/close-meeting.sh"
bash -n "$ROOT/scripts/attach-media.sh"
bash -n "$ROOT/scripts/record-approval.sh"
bash -n "$ROOT/scripts/new-coding-project.sh"
bash -n "$ROOT/scripts/reset-agent-team-state.sh"
bash -n "$ROOT/scripts/set-project-target.sh"
bash -n "$ROOT/scripts/start-agent-team-worktrees.sh"
bash -n "$ROOT/scripts/agent-status.sh"
bash -n "$ROOT/scripts/agent-inbox.sh"
bash -n "$ROOT/scripts/create-agent-task.sh"
bash -n "$ROOT/scripts/route-agent.sh"
bash -n "$ROOT/scripts/check-ready.sh"
bash -n "$ROOT/scripts/check-done.sh"
bash -n "$ROOT/scripts/run-quality-gates.sh"
bash -n "$ROOT/scripts/log-event.sh"
bash -n "$ROOT/scripts/update-agent-state.sh"
bash -n "$ROOT/scripts/sync-agent-state.sh"
bash -n "$ROOT/scripts/claim-route.sh"
bash -n "$ROOT/scripts/complete-route.sh"
bash -n "$ROOT/scripts/block-route.sh"
bash -n "$ROOT/scripts/cancel-route.sh"
bash -n "$ROOT/scripts/dispatch-routes.sh"
bash -n "$ROOT/scripts/check-ownership.sh"
bash -n "$ROOT/scripts/check-memory.sh"
bash -n "$ROOT/scripts/check-route-budget.sh"
bash -n "$ROOT/scripts/check-stale-routes.sh"
bash -n "$ROOT/scripts/recover-stale-routes.sh"
bash -n "$ROOT/scripts/check-agent-config.sh"
bash -n "$ROOT/scripts/check-secrets.sh"
bash -n "$ROOT/scripts/check-milestone-budget.sh"
bash -n "$ROOT/scripts/validate-structured-state.sh"
bash -n "$ROOT/scripts/validate-route-state.sh"
bash -n "$ROOT/scripts/route-status.sh"

bash "$ROOT/tests/test-auto-codex-agent-team.sh"
bash "$ROOT/tests/test-coding-company-functional-layer.sh"
bash "$ROOT/tests/test-routing-reliability.sh"

for role in "${AGENT_ROLES[@]}"; do
  for role_file in \
    ".agents/prompts/$role.md" \
    ".agents/skills/$role.md" \
    ".agents/memory/$role.md" \
    ".agents/agent-config/$role.yaml" \
    ".agents/ownership/$role.paths" \
    ".agents/inbox/$role.md" \
    ".agents/agent-log/$role.md"; do
    if [ ! -f "$ROOT/$role_file" ]; then
      printf "Missing role file for %s: %s\n" "$role" "$role_file" >&2
      exit 1
    fi
  done
  "$ROOT/scripts/check-agent-config.sh" "$role" >/dev/null
done

if command -v tmux >/dev/null 2>&1; then
  tmp_session="agent-team-validate-$$"
  tmux -f "$ROOT/.tmux.agent-team.conf" new-session -d -s "$tmp_session" -c "$ROOT" -n smoke
  tmux kill-session -t "$tmp_session"
fi

printf "Agent workflow scaffold validation passed.\n"
