#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/scripts/agent-roles.sh"
missing=0

required_files=(
  "AGENTS.md"
  "agent-control/context-map.md"
  "agent-control/agent-policy.md"
  "agent-control/company/README.md"
  "agent-control/company/agent-profiles.jsonl"
  "agent-control/company/projects.jsonl"
  "agent-control/meetings/README.md"
  "agent-control/media/README.md"
  "agent-control/media/manifest.jsonl"
  "agent-control/approvals.jsonl"
  "agent-control/evaluation-suite.md"
  "agent-control/failure-recovery.md"
  "agent-control/adaptation-guide.md"
  "agent-control/design-notes.md"
  "agent-control/product-requirements.md"
  "agent-control/qa-plan.md"
  "agent-control/release-notes.md"
  "agent-control/research-notes.md"
  "agent-control/performance-report.md"
  "agent-control/intake-notes.md"
  "agent-control/project-target.md"
  "agent-control/brief.md"
  "agent-control/sop.md"
  "agent-control/roles.md"
  "agent-control/architecture.md"
  "agent-control/decisions.md"
  "agent-control/definition-of-ready.md"
  "agent-control/definition-of-done.md"
  "agent-control/conflict-resolution.md"
  "agent-control/task-board.md"
  "agent-control/handoffs.md"
  "agent-control/quality-gates.md"
  "agent-control/change-control.md"
  "agent-control/change-request.md"
  "agent-control/workflow-state.md"
  "agent-control/routing-matrix.md"
  "agent-control/route-schema.md"
  "agent-control/routes/README.md"
  "agent-control/events.jsonl"
  "agent-control/memory-policy.md"
  "agent-control/sync-policy.md"
  "agent-control/route-budget.md"
  "agent-control/secrets-policy.md"
  "agent-control/milestone-budget.md"
  "agent-control/validation-report.md"
  "agent-control/review-report.md"
  "agent-control/security-report.md"
  "agent-control/prompts/orchestrator.md"
  "agent-control/prompts/intake-orchestrator.md"
  "agent-control/prompts/cto.md"
  "agent-control/prompts/pm.md"
  "agent-control/prompts/frontend.md"
  "agent-control/prompts/backend.md"
  "agent-control/prompts/validation.md"
  "agent-control/prompts/final-cto-review.md"
  "agent-control/prompts/final-acceptance.md"
  "agent-control/prompts/reviewer.md"
  "agent-control/prompts/security.md"
  "agent-control/prompts/integration.md"
  "agent-control/agent-log/orchestrator.md"
  "agent-control/agent-log/reviewer.md"
  "agent-control/agent-log/security.md"
  "agent-control/skills/orchestrator.md"
  "agent-control/skills/cto.md"
  "agent-control/skills/pm.md"
  "agent-control/skills/frontend.md"
  "agent-control/skills/backend.md"
  "agent-control/skills/validation.md"
  "agent-control/skills/reviewer.md"
  "agent-control/skills/security.md"
  "agent-control/skills/integration.md"
  "agent-control/memory/orchestrator.md"
  "agent-control/memory/cto.md"
  "agent-control/memory/pm.md"
  "agent-control/memory/frontend.md"
  "agent-control/memory/backend.md"
  "agent-control/memory/validation.md"
  "agent-control/memory/reviewer.md"
  "agent-control/memory/security.md"
  "agent-control/memory/integration.md"
  "agent-control/agent-config/orchestrator.yaml"
  "agent-control/agent-config/cto.yaml"
  "agent-control/agent-config/pm.yaml"
  "agent-control/agent-config/frontend.yaml"
  "agent-control/agent-config/backend.yaml"
  "agent-control/agent-config/validation.yaml"
  "agent-control/agent-config/reviewer.yaml"
  "agent-control/agent-config/security.yaml"
  "agent-control/agent-config/integration.yaml"
  "agent-control/ownership/orchestrator.paths"
  "agent-control/ownership/cto.paths"
  "agent-control/ownership/pm.paths"
  "agent-control/ownership/frontend.paths"
  "agent-control/ownership/backend.paths"
  "agent-control/ownership/validation.paths"
  "agent-control/ownership/reviewer.paths"
  "agent-control/ownership/security.paths"
  "agent-control/ownership/integration.paths"
  "agent-control/ownership/ignored-synced.paths"
  "agent-control/schemas/orchestrator-output.md"
  "agent-control/schemas/cto-output.md"
  "agent-control/schemas/pm-output.md"
  "agent-control/schemas/implementation-output.md"
  "agent-control/schemas/validation-output.md"
  "agent-control/schemas/reviewer-output.md"
  "agent-control/schemas/security-output.md"
  "agent-control/schemas/integration-output.md"
  "agent-control/schemas/agent-profile.md"
  "agent-control/schemas/agent-state.md"
  "agent-control/schemas/meeting-output.md"
  "agent-control/schemas/media-attachment.md"
  "agent-control/schemas/approval-record.md"
  "agent-control/state/README.md"
  "agent-control/state/projects.jsonl"
  "agent-control/state/agents.jsonl"
  "agent-control/state/routes.jsonl"
  "agent-control/state/tasks.jsonl"
  "agent-control/state/findings.jsonl"
  "agent-control/state/meetings.jsonl"
  "agent-control/state/media.jsonl"
  "agent-control/state/approvals.jsonl"
  "visual-media/index.html"
  "visual-media/styles.css"
  "visual-media/app.js"
  "visual-media/agent_office_server.py"
  "visual-media/README.md"
  "agent-control/inbox/orchestrator.md"
  "agent-control/inbox/cto.md"
  "agent-control/inbox/pm.md"
  "agent-control/inbox/frontend.md"
  "agent-control/inbox/backend.md"
  "agent-control/inbox/validation.md"
  "agent-control/inbox/reviewer.md"
  "agent-control/inbox/security.md"
  "agent-control/inbox/integration.md"
  ".tmux.agent-team.conf"
  "scripts/start-agent-team.sh"
  "scripts/agent-roles.sh"
  "scripts/codex-role.sh"
  "scripts/trust-codex-projects.sh"
  "scripts/wait-for-agent-sessions.sh"
  "scripts/watch-routes.sh"
  "scripts/company-status.sh"
  "scripts/create-meeting.sh"
  "scripts/close-meeting.sh"
  "scripts/attach-media.sh"
  "scripts/record-approval.sh"
  "scripts/new-coding-project.sh"
  "scripts/reset-agent-team-state.sh"
  "scripts/set-project-target.sh"
  "scripts/start-agent-team-worktrees.sh"
  "scripts/check-ready.sh"
  "scripts/check-done.sh"
  "scripts/run-quality-gates.sh"
  "scripts/log-event.sh"
  "scripts/update-agent-state.sh"
  "scripts/sync-agent-state.sh"
  "scripts/claim-route.sh"
  "scripts/complete-route.sh"
  "scripts/block-route.sh"
  "scripts/cancel-route.sh"
  "scripts/dispatch-routes.sh"
  "scripts/check-ownership.sh"
  "scripts/check-memory.sh"
  "scripts/check-route-budget.sh"
  "scripts/check-stale-routes.sh"
  "scripts/recover-stale-routes.sh"
  "scripts/detect-agent-health.sh"
  "scripts/checkpoint-agent-context.sh"
  "scripts/recover-agent-session.sh"
  "scripts/monitor-agent-sessions.sh"
  "scripts/repair-role-readiness.sh"
  "scripts/check-agent-config.sh"
  "scripts/check-secrets.sh"
  "scripts/check-milestone-budget.sh"
  "scripts/validate-structured-state.sh"
  "scripts/validate-route-state.sh"
  "scripts/route-status.sh"
  "scripts/route-db.sh"
  "scripts/record-route-run.sh"
  "scripts/heartbeat-routes.sh"
  "scripts/start-agent-office-dashboard.sh"
  "scripts/start-visual-media-dashboard.sh"
)

for file in "${required_files[@]}"; do
  if [ ! -f "$ROOT/$file" ]; then
    printf "Missing: %s\n" "$file" >&2
    missing=1
  fi
done

if [ "$missing" -ne 0 ]; then
  exit 1
fi

bash -n "$ROOT/scripts/start-agent-team.sh"
bash -n "$ROOT/scripts/agent-roles.sh"
bash -n "$ROOT/scripts/codex-role.sh"
bash -n "$ROOT/scripts/trust-codex-projects.sh"
bash -n "$ROOT/scripts/wait-for-agent-sessions.sh"
bash -n "$ROOT/scripts/watch-routes.sh"
bash -n "$ROOT/scripts/company-status.sh"
bash -n "$ROOT/scripts/create-meeting.sh"
bash -n "$ROOT/scripts/close-meeting.sh"
bash -n "$ROOT/scripts/attach-media.sh"
bash -n "$ROOT/scripts/record-approval.sh"
bash -n "$ROOT/scripts/new-coding-project.sh"
bash -n "$ROOT/scripts/reset-agent-team-state.sh"
bash -n "$ROOT/scripts/set-project-target.sh"
bash -n "$ROOT/scripts/start-agent-team-worktrees.sh"
bash -n "$ROOT/scripts/agent-status.sh"
bash -n "$ROOT/scripts/agent-inbox.sh"
bash -n "$ROOT/scripts/create-agent-task.sh"
bash -n "$ROOT/scripts/route-agent.sh"
bash -n "$ROOT/scripts/check-ready.sh"
bash -n "$ROOT/scripts/check-done.sh"
bash -n "$ROOT/scripts/run-quality-gates.sh"
bash -n "$ROOT/scripts/log-event.sh"
bash -n "$ROOT/scripts/update-agent-state.sh"
bash -n "$ROOT/scripts/sync-agent-state.sh"
bash -n "$ROOT/scripts/claim-route.sh"
bash -n "$ROOT/scripts/complete-route.sh"
bash -n "$ROOT/scripts/block-route.sh"
bash -n "$ROOT/scripts/cancel-route.sh"
bash -n "$ROOT/scripts/dispatch-routes.sh"
bash -n "$ROOT/scripts/check-ownership.sh"
bash -n "$ROOT/scripts/check-memory.sh"
bash -n "$ROOT/scripts/check-route-budget.sh"
bash -n "$ROOT/scripts/check-stale-routes.sh"
bash -n "$ROOT/scripts/recover-stale-routes.sh"
bash -n "$ROOT/scripts/detect-agent-health.sh"
bash -n "$ROOT/scripts/checkpoint-agent-context.sh"
bash -n "$ROOT/scripts/recover-agent-session.sh"
bash -n "$ROOT/scripts/monitor-agent-sessions.sh"
bash -n "$ROOT/scripts/repair-role-readiness.sh"
bash -n "$ROOT/scripts/check-agent-config.sh"
bash -n "$ROOT/scripts/check-secrets.sh"
bash -n "$ROOT/scripts/check-milestone-budget.sh"
bash -n "$ROOT/scripts/validate-structured-state.sh"
bash -n "$ROOT/scripts/validate-route-state.sh"
bash -n "$ROOT/scripts/route-status.sh"
bash -n "$ROOT/scripts/route-db.sh"
bash -n "$ROOT/scripts/record-route-run.sh"
bash -n "$ROOT/scripts/heartbeat-routes.sh"
bash -n "$ROOT/scripts/start-agent-office-dashboard.sh"
bash -n "$ROOT/scripts/start-visual-media-dashboard.sh"
python3 -m py_compile "$ROOT/visual-media/agent_office_server.py"

bash "$ROOT/tests/test-auto-codex-agent-team.sh"
bash "$ROOT/tests/test-coding-company-functional-layer.sh"
bash "$ROOT/tests/test-routing-reliability.sh"
bash "$ROOT/tests/test-agent-session-recovery.sh"
bash "$ROOT/tests/test-runtime-priorities.sh"
bash "$ROOT/tests/test-agent-office-dashboard.sh"
bash "$ROOT/tests/test-visual-media-functional-layer.sh"

for role in "${AGENT_ROLES[@]}"; do
  for role_file in \
    "agent-control/prompts/$role.md" \
    "agent-control/skills/$role.md" \
    "agent-control/memory/$role.md" \
    "agent-control/agent-config/$role.yaml" \
    "agent-control/ownership/$role.paths" \
    "agent-control/inbox/$role.md" \
    "agent-control/agent-log/$role.md"; do
    if [ ! -f "$ROOT/$role_file" ]; then
      printf "Missing role file for %s: %s\n" "$role" "$role_file" >&2
      exit 1
    fi
  done
  "$ROOT/scripts/check-agent-config.sh" "$role" >/dev/null
done

if command -v tmux >/dev/null 2>&1; then
  tmp_session="agent-team-validate-$$"
  tmux -f "$ROOT/.tmux.agent-team.conf" new-session -d -s "$tmp_session" -c "$ROOT" -n smoke
  tmux kill-session -t "$tmp_session"
fi

printf "Agent workflow scaffold validation passed.\n"
